local null_ls = require("null-ls")

null_ls.setup({
	sources = {
		null_ls.builtins.diagnostics.cspell,
		null_ls.builtins.code_actions.cspell,
		null_ls.builtins.diagnostics.eslint_d,
		null_ls.builtins.code_actions.eslint_d,
		null_ls.builtins.formatting.eslint_d,
		null_ls.builtins.code_actions.gitsigns,
--		null_ls.builtins.code_actions.refactoring,
		null_ls.builtins.diagnostics.shellcheck,
		null_ls.builtins.code_actions.shellcheck,
		null_ls.builtins.completion.luasnip,
		null_ls.builtins.diagnostics.buildifier,
		null_ls.builtins.formatting.buildifier,
		null_ls.builtins.diagnostics.commitlint,
		null_ls.builtins.diagnostics.dotenv_linter,
		null_ls.builtins.diagnostics.golangci_lint,
		null_ls.builtins.diagnostics.jsonlint,
		null_ls.builtins.diagnostics.luacheck,
		null_ls.builtins.diagnostics.markdownlint,
		null_ls.builtins.diagnostics.protolint,
		null_ls.builtins.diagnostics.revive,
		null_ls.builtins.diagnostics.tsc,
		null_ls.builtins.formatting.fixjson,
		null_ls.builtins.formatting.gofmt,
		null_ls.builtins.formatting.goimports_reviser,
		null_ls.builtins.formatting.jq,
		null_ls.builtins.formatting.markdownlint,
		null_ls.builtins.formatting.pg_format,
		null_ls.builtins.formatting.prettierd,
		null_ls.builtins.formatting.prettier_eslint,
		null_ls.builtins.formatting.protolint,
		null_ls.builtins.formatting.taplo,
	}
})
