customCommands:
  - command: "gh pr create --fill --web"
    context: "global"
    key: "<c-r>"
    loadingText: "Creating pull request on GitHub"
  - command: "git cz c"
    context: "files"
    description: "commit with commitizen"
    key: "C"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - command: "gh browse"
    context: "files"
    description: "Browse the repository on GitHub"
    key: "b"
  - command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
    description: "Browse the commit on GitHub"
    key: "b"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
