customCommands:
  - command: "gh pr create --fill --web"
    context: "global"
    key: "<c-r>"
    loadingText: "Creating pull request on GitHub"
  - command: "git cz c"
    context: "files"
    description: "commit with commitizen"
    key: "C"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - command: "gh browse"
    context: "files"
    description: "Browse the repository on GitHub"
    key: "b"
  - command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
    description: "Browse the commit on GitHub"
    key: "b"
git:
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 80
  paging:
    colorArg: always
    pager: delta --tabs=2 --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  filterMode: "fuzzy"
  theme:
    activeBorderColor:
      - "#8aadf4"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    selectedRangeBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#8aadf4"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
