theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

